name: Lint

on:
  pull_request:
    paths:
      - '**.py'

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install isort
        run: pip install isort

      - name: Run isort
        run: isort .

      - name: List changed files
        run: CHANGED_FILES=$(git diff --name-only HEAD) >> $GITHUB_ENV

      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files:
          commit-message: ':robot: run isort'
          ref: ${{ GITHUB_REF }}
